### ISSUE TITLE
Arbitrarily Moving Observer

### ISSUE THREAD

**Issue by christianhauschel** [OpenMDAO/AcousticAnalogies.jl#10]
Hello, 

Does this code also support a moving observer with non-constant velocity?

Thank you.

**Comment by dingraha** [comment]
By non-constant velocity, do you mean the rotor translating at non-constant rate, or the RPM increasing/decreasing, or something else?

**Comment by christianhauschel** [comment]
Both, I'm trying to predict the noise of a quadcopter with fluctuating RPM in dynamic flight.
